In [1]:
import pandas as pd
df = pd.read_csv("https://github.com/codeforamerica/ohana-api/raw/master/data/sample-csv/addresses.csv")
df

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [5]:
# FILE OPERATIONS USING PANDAS
df1 = pd.read_csv("https://github.com/codeforamerica/ohana-api/raw/master/data/sample-csv/addresses.csv")
type(df)

pandas.core.frame.DataFrame

In [14]:
df1 = pd.read_csv("https://github.com/codeforamerica/ohana-api/raw/master/data/sample-csv/addresses.csv", sep=',',header=None, skiprows=[3,4,5],names=[0,1,2,3,4,5,6,'Abhinavkxmkon'])
df1

,0,1,2,3,4,5,6,Abhinavkxmkon
0,id,location_id,address_1,address_2,city,state_province,postal_code,country
1,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
2,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
3,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
4,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
5,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
7,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
8,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
9,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
10,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
11,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
12,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
13,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
14,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
15,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
16,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
17,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
18,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [17]:
df.to_csv("abc.csv")
ad = pd.read_csv("abc.csv")
ad

,Unnamed: 0,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [18]:
ad.describe()

       Unnamed: 0         id  location_id
count   21.000000  21.000000    21.000000
mean    10.000000  11.000000    11.095238
std      6.204837   6.204837     6.363213
min      0.000000   1.000000     1.000000
25%      5.000000   6.000000     6.000000
50%     10.000000  11.000000    11.000000
75%     15.000000  16.000000    16.000000
max     20.000000  21.000000    22.000000

In [21]:
ad.dtypes

Unnamed: 0         int64
id                 int64
location_id        int64
address_1         object
address_2         object
city              object
state_province    object
postal_code       object
country           object
dtype: object

In [22]:
ad[ad.dtypes[ad.dtypes=="object"].index]

,address_1,address_2,city,state_province,postal_code,country
0,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,123 El Camino Real,NaN,Belmont,CA,94002,US
20,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [26]:
ad.dtypes[ad.dtypes=="object"]

address_1         object
address_2         object
city              object
state_province    object
postal_code       object
country           object
dtype: object

In [27]:
[ad.dtypes=="object"]

[Unnamed: 0        False
 id                False
 location_id       False
 address_1          True
 address_2          True
 city               True
 state_province     True
 postal_code        True
 country            True
 dtype: bool]

In [29]:
ad[ad.dtypes[ad.dtypes=="object"].index].describe()

,address_1,address_2,city,state_province,postal_code,country
count,21,2,21,21,21,21
unique,16,2,7,1,12,1
top,24 Second Avenue,2nd Floor,Redwood City,CA,94063,US
freq,4,1,8,21,6,21

In [32]:
ad.columns

Index(['Unnamed: 0', 'id', 'location_id', 'address_1', 'address_2', 'city',
       'state_province', 'postal_code', 'country'],
      dtype='object')

In [37]:
ad.head()

,Unnamed: 0,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US

In [36]:
ad.tail()

,Unnamed: 0,id,location_id,address_1,address_2,city,state_province,postal_code,country
16,16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [39]:
pd.Categorical(ad)

['Unnamed: 0', 'id', 'location_id', 'address_1', 'address_2', 'city', 'state_province', 'postal_code', 'country']
Categories (9, object): ['Unnamed: 0', 'address_1', 'address_2', 'city', ..., 'id', 'location_id',
                         'postal_code', 'state_province']

In [41]:
pd.Categorical(ad["state_province"])

['CA', 'CA', 'CA', 'CA', 'CA', ..., 'CA', 'CA', 'CA', 'CA', 'CA']
Length: 21
Categories (1, object): ['CA']

In [42]:
type(ad.dtypes)

pandas.core.series.Series

In [45]:
# SERIES IN PANDAS
av= df.dtypes
av

id                 int64
location_id        int64
address_1         object
address_2         object
city              object
state_province    object
postal_code       object
country           object
dtype: object

In [46]:
av["address_1"]

dtype('O')

In [47]:
av['location_id']

dtype('int64')

In [49]:
av[0]

<ipython-input-49-c474f6256c68>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  av[0]

dtype('int64')

In [54]:
n= [0.45,45,33,4,6,7,89,9,2235,4,55,"abhinav",'kjernoj']

In [56]:
n[0]

0.45

In [57]:
n[0:6]

[0.45, 45, 33, 4, 6, 7]

In [58]:
n[0:68:3]

[0.45, 4, 89, 4, 'kjernoj']

In [59]:
n[::-1]

['kjernoj', 'abhinav', 55, 4, 2235, 9, 89, 7, 6, 4, 33, 45, 0.45]

In [60]:
n

[0.45, 45, 33, 4, 6, 7, 89, 9, 2235, 4, 55, 'abhinav', 'kjernoj']

In [61]:
df

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [62]:
df.head()

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US

In [63]:
df.tail()

,id,location_id,address_1,address_2,city,state_province,postal_code,country
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [64]:
df["city"]

0            Redwood City
1               San Mateo
2               San Mateo
3               San Mateo
4               San Mateo
5              Menlo Park
6              Menlo Park
7              Menlo Park
8            Redwood City
9            Redwood City
10           Redwood City
11           Redwood City
12           Redwood City
13           Redwood City
14          San Francisco
15              Sunnyvale
16    South San Francisco
17           Redwood City
18              San Mateo
19                Belmont
20          San Francisco
Name: city, dtype: object

In [65]:
type(df["city"])

pandas.core.series.Series

In [67]:
df[["city"]]

                   city
0          Redwood City
1             San Mateo
2             San Mateo
3             San Mateo
4             San Mateo
5            Menlo Park
6            Menlo Park
7            Menlo Park
8          Redwood City
9          Redwood City
10         Redwood City
11         Redwood City
12         Redwood City
13         Redwood City
14        San Francisco
15            Sunnyvale
16  South San Francisco
17         Redwood City
18            San Mateo
19              Belmont
20        San Francisco

In [69]:
df[["city"]][4:100:2]

                   city
4             San Mateo
6            Menlo Park
8          Redwood City
10         Redwood City
12         Redwood City
14        San Francisco
16  South San Francisco
18            San Mateo
20        San Francisco

In [72]:
df[["city"]][-1:0:-2]

                   city
20        San Francisco
18            San Mateo
16  South San Francisco
14        San Francisco
12         Redwood City
10         Redwood City
8          Redwood City
6            Menlo Park
4             San Mateo
2             San Mateo

In [73]:
# We can use list of list to avoid these situations
df[-1]

KeyError: -1

In [74]:
list(df["address_1"][::2])

['2600 Middlefield Road',
 '24 Second Avenue',
 '24 Second Avenue',
 '500 Arbor Road',
 '2510 Middlefield Road',
 '2140 Euclid Avenue.',
 '399 Marine Parkway.',
 '1500 Valencia Street',
 '409 South Spruce Avenue',
 '19 West 39th Avenue',
 '2013 Avenue of the fellows']

In [76]:
df.dtypes

id                 int64
location_id        int64
address_1         object
address_2         object
city              object
state_province    object
postal_code       object
country           object
dtype: object

In [77]:
df.dtypes == 'object'

id                False
location_id       False
address_1          True
address_2          True
city               True
state_province     True
postal_code        True
country            True
dtype: bool

In [78]:
df.dtypes[df.dtypes == 'object']

address_1         object
address_2         object
city              object
state_province    object
postal_code       object
country           object
dtype: object

In [80]:
df9 = df.dtypes[df.dtypes == 'object']

In [81]:
df9.index

Index(['address_1', 'address_2', 'city', 'state_province', 'postal_code',
       'country'],
      dtype='object')

In [82]:
df[df.dtypes[df.dtypes == 'object'].index]

,address_1,address_2,city,state_province,postal_code,country
0,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,123 El Camino Real,NaN,Belmont,CA,94002,US
20,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [83]:
df10 = df[df.dtypes[df.dtypes == 'object'].index]

In [84]:
df10.describe

<bound method NDFrame.describe of                      address_1  address_2                 city state_province  \
0        2600 Middlefield Road        NaN         Redwood City             CA
1             24 Second Avenue        NaN            San Mateo             CA
2             24 Second Avenue        NaN            San Mateo             CA
3             24 Second Avenue        NaN            San Mateo             CA
4             24 Second Avenue        NaN            San Mateo             CA
5            800 Middle Avenue        NaN           Menlo Park             CA
6               500 Arbor Road        NaN           Menlo Park             CA
7            800 Middle Avenue        NaN           Menlo Park             CA
8        2510 Middlefield Road        NaN         Redwood City             CA
9        1044 Middlefield Road        NaN         Redwood City             CA
10         2140 Euclid Avenue.        NaN         Redwood City             CA
11       1044 Middlefield Road  2nd Floor         Redwood City             CA
12         399 Marine Parkway.        NaN         Redwood City             CA
13          660 Veterans Blvd.        NaN         Redwood City             CA
14        1500 Valencia Street        NaN        San Francisco             CA
15         1161 South Bernardo        NaN            Sunnyvale             CA
16     409 South Spruce Avenue        NaN  South San Francisco             CA
17            114 Fifth Avenue        NaN         Redwood City             CA
18         19 West 39th Avenue        NaN            San Mateo             CA
19          123 El Camino Real        NaN              Belmont             CA
20  2013 Avenue of the fellows  Suite 100        San Francisco             CA

   postal_code country
0        94063      US
1        94401      US
2        94403      US
3        94401      US
4        94401      US
5   94025-9881      US
6        94025      US
7   94025-9881      US
8        94063      US
9        94063      US
10       94061      US
11       94063      US
12       94065      US
13       94063      US
14       94110      US
15       94087      US
16       94080      US
17       94063      US
18       94403      US
19       94002      US
20       94103      US  >

In [85]:
df10.columns

Index(['address_1', 'address_2', 'city', 'state_province', 'postal_code',
       'country'],
      dtype='object')

In [87]:
df10["city"]

0            Redwood City
1               San Mateo
2               San Mateo
3               San Mateo
4               San Mateo
5              Menlo Park
6              Menlo Park
7              Menlo Park
8            Redwood City
9            Redwood City
10           Redwood City
11           Redwood City
12           Redwood City
13           Redwood City
14          San Francisco
15              Sunnyvale
16    South San Francisco
17           Redwood City
18              San Mateo
19                Belmont
20          San Francisco
Name: city, dtype: object

In [88]:
df10[["city","address_1"]]

                   city                   address_1
0          Redwood City       2600 Middlefield Road
1             San Mateo            24 Second Avenue
2             San Mateo            24 Second Avenue
3             San Mateo            24 Second Avenue
4             San Mateo            24 Second Avenue
5            Menlo Park           800 Middle Avenue
6            Menlo Park              500 Arbor Road
7            Menlo Park           800 Middle Avenue
8          Redwood City       2510 Middlefield Road
9          Redwood City       1044 Middlefield Road
10         Redwood City         2140 Euclid Avenue.
11         Redwood City       1044 Middlefield Road
12         Redwood City         399 Marine Parkway.
13         Redwood City          660 Veterans Blvd.
14        San Francisco        1500 Valencia Street
15            Sunnyvale         1161 South Bernardo
16  South San Francisco     409 South Spruce Avenue
17         Redwood City            114 Fifth Avenue
18            San Mateo         19 West 39th Avenue
19              Belmont          123 El Camino Real
20        San Francisco  2013 Avenue of the fellows

In [89]:
df10["city"].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
Name: city, dtype: bool